### ISSUE TITLE
Can you provide a sample of reading pictures, thank you

### ISSUE THREAD

**Issue by kingodragon** [RoCorbera/BlueVGA#12]
I want to show an animation for it, but I don't know how.

**Comment by RoCorbera** [comment]
There is no way to do it. 
Pictures usually have 24 bits per pixel.
This library only supports 8 colors (3 bits).
It also only works with Tiles, which are predefined such as in a font bitmap.
It is not a Display.

**Comment by RoCorbera** [comment]
You should move to another chip, such as ESP32.

It has a nicer VGA library that can run animations from a SDCard using a resolution such as 320x240 with 14bits per pixel (4096 colors). This may work a lot better.
https://github.com/bitluni/ESP32VGA
https://www.youtube.com/watch?v=G70CZLPjsXU

**Comment by kingodragon** [comment]
> You should move to another chip, such as ESP32.
> 
> It has a nicer VGA library that can run animations from a SDCard using a resolution such as 320x240 with 14bits per pixel (4096 colors). This may work a lot better. https://github.com/bitluni/ESP32VGA https://www.youtube.com/watch?v=G70CZLPjsXU



> There is no way to do it. Pictures usually have 24 bits per pixel. This library only supports 8 colors (3 bits). It also only works with Tiles, which are predefined such as in a font bitmap. It is not a Display.

I figured it out, thanks for your patience

**Comment by RoCorbera** [comment]
Please kindly post here the solution for other users. Thanks!
